#!/usr/bin/env python3

# Script:                   ops-401d2-challenge-class02.py                       
# Author:                   Emilio Muniz                       
# Date of latest revision:  4/06/2021    
# Purpose:                  Python script creating uptime sensor.

# Declaration of variables:


# Declaration of functions:

# Main
#import time
#import datetime
import os

ip_list = ["127.0.0.1", "10.0.0.7"]
for ip in ip_list:
    response = os.popen(f"ping {ip}").read()
    if "Received" in response:
        print(f"UP {ip} Ping Successful")
    else:
        print(f"DOWN {ip} Ping Unsuccessful")




