#!/usr/bin/env python3

# Script:                   ops-401d2-challenge-class02.py                       
# Author:                   Emilio Muniz                       
# Date of latest revision:  4/07/2021    
# Purpose:                  Python script creating uptime sensor with email alert.

# Declaration of variables:


# Declaration of functions:

# Main
import time, datetime, os, smtplib

server = smtplib.SMTP_SSL("smtp.gmail.com", 465)
server.ehlo()

server.login("emiliomuniz1@gmail.com", "B********!!")

msg1 = "Attention! \n Network Host Status is DOWN."
msg2 = "Attention! \n Network Host Status is UP."

ip_list = ["8.8.8.8", "10.0.0.8"]
for ip in ip_list:
    response = os.popen(f"ping -c 1 {ip}").read()
    if "1 received" in response:
        server.sendmail("emiliomunizphoto@gmail.com", "emiliomuniz1@gmail.com", msg2)
        server.quit()
    else:
        server.sendmail("emiliomunizphoto@gmail.com", "emiliomuniz1@gmail.com", msg1)
        server.quit()

# End
# References: https://frontrowviews.com/Home/Event/Play/605ccd1cfd9afc15c8807722 
