#!/usr/bin/env python3

# Script:                   ops-401d2-challenge-class02.py                       
# Author:                   Emilio Muniz                       
# Date of latest revision:  4/06/2021    
# Purpose:                  Python script creating uptime sensor.

# Declaration of variables:


# Declaration of functions:

# Main
import time, datetime, os

ip_list = ["8.8.8.8", "10.0.0.8"]
for ip in ip_list:
    response = os.popen(f"ping -c 1 {ip}").read()
    if "1 received" in response:
        print(f"UP {ip} Ping Successful")
    else:
        print(f"DOWN {ip} Ping Unsuccessful")




