#!/usr/bin/env python3

# Script:                   ops-401d2-challenge-class02.py                       
# Author:                   Emilio Muniz                       
# Date of latest revision:  4/06/2021    
# Purpose:                  Python script creating uptime sensor.

# Declaration of variables:


# Declaration of functions:

# Main
import time, datetime, os

ip_list = ["8.8.8.8"]
for ip in ip_list:
    response = os.popen(f"ping -c 1 {ip}").read()
    if "1 received" in response:
        print(f"UP {ip} Network Active")
    else:
        print(f"DOWN {ip} Network Inactive")

while True:
   now = datetime.datetime.now()
   print(str(now) + " " + response)
   time.sleep( 2 )
   print("Network Active")

# End
# References: https://www.youtube.com/watch?v=PTUhiDnYrbs




